### ISSUE TITLE
How to Change UI Template of Tohora in BalenaDash

### ISSUE THREAD

**Issue by jensJJ** [mozz100/screenserve#8]
Hello,
thank you for the great tool. I am using it with balenaDash and wanted to change the logo and colors of Tohora. How can I replace the logos and templates in balenaDash?

I have copied templates into /home/chromium/tohora/templates, but it won't show the images. I believe I have to use the go build command on the whole folder,  but I get no package found.

https://forums.balena.io/t/balenadash-tohora-change-ui/118142/2

Is there an easy way to change the UI? Thanks

**Comment by mozz100** [comment]
You don't need to rebuild Tohora to change the HTML - just make edits to `index.html`.

Here - https://github.com/mozz100/tohora/blob/master/handlers/handlers.go#L14 - is where that's set up.

Tohora responds to http requests for `/` by compiling `templates/index.html` and that's it - no other static files like CSS or javascript.  The path will be relative to the working directory when Tohora is running.  On my balena-dash raspberry pi, Tohora runs in `/` and the file `/templates/index.html` is the template that's used.  I see that the balena-dash project now has various Dockerfiles for different architectures so you need to check which place Tohora is running from (use the balena dashboard, open a terminal in the `kiosk` container and type `pwd`.  Your path looks correct for some architectures.

So - in summary - check `pwd` for your `kiosk` container.  Remember that no static file serving is taking place - just `index.html`.  It should be quite easy to make Tohora serve static files - just not a use case for me: I'm not a designer.  PRs welcomed!

Happy to help further, just let me know

**Comment by jensJJ** [comment]
Hi, thank you. I will try that and hope it works.

**Comment by jensJJ** [comment]
I want to place the tohora folder locally inside the kiosk folder, so it doesnt have to us go get github.com...

```
# build tohora from source
FROM balenalib/raspberrypi3-golang as builder

RUN go get -d -v github.com/mozz100/tohora/...

WORKDIR /go/src/github.com/mozz100/tohora

RUN go build 

```

I do

```
FROM balenalib/raspberrypi3-golang as builder

WORKDIR /go/src

COPY ./tohora ./tohora

WORKDIR /go/src/tohora

RUN go build 
```

It cannot build tohora no go package found. How can I fix this? Thanks

**Comment by mozz100** [comment]
I'm still not sure why you're rebuilding the binary to make changes to the html template.

In the line in your `Dockerfile` where you do `COPY ./tohora ./tohora` you should are copying a whole source code directory, including the `subprocess` and `handlers` subdirectories.  But when it ends up inside the docker image, the `import` statements aren't going to work - see for example https://github.com/mozz100/tohora/blob/master/handlers/handlers.go#L9

Because [there's no relative import](https://stackoverflow.com/questions/38517593/relative-imports-in-go) in Go (best of my knowledge), you'd have to alter the source code to make it build in a Go environment where `$GOPATH/github.com/mozz100/tohora/subprocess` didn't exist.

If you do find a neat way to do this, please let me know how you got on.  `tohora` was my first ever golang project and I had never used the language beforehand.

**Comment by mozz100** [comment]
Hi @jensJJ - did you make progress with this?  Keen to hear how you got on, or if I can help further

**Comment by jensJJ** [comment]
Hi, @mozz100 I tried to compile the holder folder, but failed every time. So I couldn't achieve what I was planning to do and change the static images css js and index.html.

**Comment by mozz100** [comment]
Sorry to hear that.  To reiterate: tohora only serves `index.html` at `/` and you don't need to compile anything to change that.  Unless you have a reason why you can't, I'd suggest you just "hotlink" to external CSS and JS (the existing template does this).  To do so you just need to replace `index.html` inside your docker image.

If you need help compiling, please open a separate issue with the full error message and details.
